fail if zone id can't be resolved

diff --git a/manifests/platform/cloudflare-dns/base/workflow-template.yaml b/manifests/platform/cloudflare-dns/base/workflow-template.yaml
--- a/manifests/platform/cloudflare-dns/base/workflow-template.yaml
+++ b/manifests/platform/cloudflare-dns/base/workflow-template.yaml
@@ -159,6 +159,12 @@ spec:
             -H "Authorization: Bearer $cloudflare_auth_token" \
             -H "Content-Type: application/json" | jq -r '{"result"}[] | .[0] | .id // ""')
 
+          if [[ -z "${zoneid}" ]]; then
+            echo "Unable to resolve the zone ID"
+            exit 2
+          fi
+          
+
 
           # if here, the dns record needs updating
           # get the dns record id 
